### ISSUE TITLE
bathymetry/elevation

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/geospatialRUCSBAtlas#11]
We are marrying together two rasters, that came with two separate resolutions and extents.

I think they even have different sea levels.

As part of mapping vernal pools, the water depth on campus waterbodies, and locations where water may pool in a hazardous way, we need to make our elevation raster clearly harmonious.

**Comment by brunj7** [comment]
![](https://github.com/UCSBCarpentry/geospatialRUCSBAtlas/blob/main/images/binned_dem.png)

**Comment by brunj7** [comment]
[](images/binned_dem.png)

**Comment by brunj7** [comment]
Raw data: the zip archive has one level too much of folder nesting. When unzip I end up with: `geospatialRUCSBAtlas/source_data/greatercampusDEM/greatercampusDEM/greatercampusDEM_1_1.tif`

@jonjab I do not have editing access to the Google Drive, so somebody else needs to redo the zip archive 

I will work with this path in the meantime: `geospatialRUCSBAtlas/source_data/greatercampusDEM/greatercampusDEM_1_1.tif`

**Comment by brunj7** [comment]
Actually, the script should save the DEM in the existing `downloaded_data` folder. So the final path should be
`geospatialRUCSBAtlas/downloaded_data/greatercampusDEM/greatercampusDEM/greatercampusDEM_1_1.tif`

**Comment by jonjab** [comment]
@brunj7 has created this in episode 4.
