### ISSUE TITLE
Update episode 4 to switch to the terra package as needed

### ISSUE THREAD

**Issue by brunj7** [UCSBCarpentry/geospatialRUCSBAtlas#23]

**Comment by brunj7** [comment]
Went through the code and made the updates: https://github.com/UCSBCarpentry/geospatialRUCSBAtlas/pull/24

Not sure if we want to add the code to write the raster or leave it to the participants to do it

**Comment by kristi-sara** [comment]
juliens pr merged. Seeing theres a question about writing the raster or leaving it, I'll leave this issue open for now.

**Comment by brunj7** [comment]
decided to add writing the raster to the disk

**Comment by brunj7** [comment]
Working on this I realized the resolution and extent of bathy and DEM were not matching. I updated the episode 3 projection to use DEM as reference 023c54a.

It seems sea level is at 5m in the DEM not 4. need to talk to @jonjab about this.

**Comment by brunj7** [comment]
The merge of the dem and bathy has been done. Note: we might have to revisit how to best handle the lower part of the DEM (for now has been set to NA to help with the overlap merging along the coast)
