### ISSUE TITLE
Map 2: stylized map 

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/geospatialRUCSBAtlas#8]
Highly stylized with 3 layers emphasized:
trees
water
bikeways

**Comment by jonjab** [comment]
@josenino95  where are we getting streams from in Map 2?

**Comment by josenino95** [comment]
@jonjab From here * California Streams https://data.cnra.ca.gov/dataset/california-streams

**Comment by jonjab** [comment]
- visualize the tree species by color
- make streams thicker with a fuzzy border

**Comment by josenino95** [comment]
I've made the changes suggested by Julien and Jon, so I think map 2 is pretty much ready. There are two alternatives, one with tree height and the other with tree species, both are linked in the readme.
